### ISSUE TITLE
UB in data.rs and remote.rs

### ISSUE THREAD

**Issue by hellow554** [Hakuyume/socketcan-rs#38]
https://github.com/Hakuyume/socketcan-rs/blob/c19e5938a1989e3da8a82c90d50c862b5238255b/src/frame/data.rs#L18
https://github.com/Hakuyume/socketcan-rs/blob/c19e5938a1989e3da8a82c90d50c862b5238255b/src/frame/remote.rs#L18

AFAIK, this is UB as it can be seen in the second example of https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.as_mut_ptr

I'm not 100% sure though....

**Comment by Hakuyume** [comment]
In both contexts, `inner` is initialized by zero. From my understanding, this can avoid UB.

According to the docs (https://doc.rust-lang.org/std/mem/union.MaybeUninit.html#method.zeroed),

> For example, MaybeUninit<usize>::zeroed() is initialized

**Comment by hellow554** [comment]
The question is, has `inner` a valid 0-representation?

The other option would be that `set_len` accepts a `*mut` and you use [`std::ptr::write`](https://doc.rust-lang.org/std/ptr/fn.write.html)

**Comment by Hakuyume** [comment]
Since `can_frame` is a simple struct, `can_frame` filled by zeros is valid, I think. Empty can_id and empty data is a valid state.

**Comment by hellow554** [comment]
You might be right.

Thank you again for yesterday that you merged and pushed a new version. Works well for me right now :)
